// Generated by tools/sync-sources-catalog.ts. Do not edit by hand.
// Source: https://gym.genlayer.foundation/api/benchmarks/sources-bench/sources
// Catalog generated at: 2026-05-18T10:19:12.303Z
// Synced at: 2026-05-19T15:03:07.973Z

import type { SourcesCatalog } from "./sources-catalog";

export const FALLBACK_SOURCES_CATALOG: SourcesCatalog = {
  generatedAt: "2026-05-18T10:19:12.303Z",
  count: 174,
  sources: [
  {
    "source": "allin.com",
    "status": "blocked"
  },
  {
    "source": "anera.markets",
    "status": "direct"
  },
  {
    "source": "anfp.cl",
    "status": "direct"
  },
  {
    "source": "apps.apple.com",
    "status": "direct"
  },
  {
    "source": "bfunion.bg",
    "status": "alt",
    "alternative": "www.espn.com"
  },
  {
    "source": "bo3.gg",
    "status": "direct"
  },
  {
    "source": "conmebollibertadores.com",
    "status": "direct"
  },
  {
    "source": "data.giss.nasa.gov",
    "status": "direct"
  },
  {
    "source": "democrats.org",
    "status": "alt",
    "alternative": "www.apnews.com"
  },
  {
    "source": "dimayor.com.co",
    "status": "direct"
  },
  {
    "source": "dotabuff.com",
    "status": "direct"
  },
  {
    "source": "earthquake.usgs.gov",
    "status": "direct"
  },
  {
    "source": "en.khl.ru",
    "status": "direct"
  },
  {
    "source": "eredivisie.nl",
    "status": "direct"
  },
  {
    "source": "esportsworldcup.com",
    "status": "direct"
  },
  {
    "source": "eurovision.com",
    "status": "alt",
    "alternative": "en.wikipedia.org"
  },
  {
    "source": "eurovision.tv",
    "status": "alt",
    "alternative": "en.wikipedia.org"
  },
  {
    "source": "farside.co.uk",
    "status": "blocked"
  },
  {
    "source": "finance.yahoo.com",
    "status": "blocked"
  },
  {
    "source": "fred.stlouisfed.org",
    "status": "direct"
  },
  {
    "source": "gol.gg",
    "status": "direct"
  },
  {
    "source": "hltv.org",
    "status": "blocked"
  },
  {
    "source": "hnl.hr",
    "status": "direct"
  },
  {
    "source": "kick.com",
    "status": "direct"
  },
  {
    "source": "lfpb.com.bo",
    "status": "direct"
  },
  {
    "source": "lichess.org",
    "status": "direct"
  },
  {
    "source": "liga1.pe",
    "status": "direct"
  },
  {
    "source": "ligamx.net",
    "status": "direct"
  },
  {
    "source": "liquipedia.net",
    "status": "direct"
  },
  {
    "source": "live.bilibili.com",
    "status": "direct"
  },
  {
    "source": "lmarena.ai",
    "status": "direct"
  },
  {
    "source": "lolesports.com",
    "status": "alt",
    "alternative": "liquipedia.net"
  },
  {
    "source": "nikeliga.sk",
    "status": "direct"
  },
  {
    "source": "nytimes.pressreader.com",
    "status": "blocked"
  },
  {
    "source": "play-origin.sooplive.com",
    "status": "blocked"
  },
  {
    "source": "play.sooplive.com",
    "status": "direct"
  },
  {
    "source": "portwatch.imf.org",
    "status": "direct"
  },
  {
    "source": "ppatour.com",
    "status": "alt",
    "alternative": "ppatour.com"
  },
  {
    "source": "premierlacrosseleague.com",
    "status": "direct"
  },
  {
    "source": "premierliga.ru",
    "status": "direct"
  },
  {
    "source": "pro.eslgaming.com",
    "status": "direct"
  },
  {
    "source": "rnc.org",
    "status": "alt",
    "alternative": "www.apnews.com"
  },
  {
    "source": "rollcall.com",
    "status": "alt",
    "alternative": "www.apnews.com"
  },
  {
    "source": "seekingalpha.com",
    "status": "blocked"
  },
  {
    "source": "senedd.wales",
    "status": "direct"
  },
  {
    "source": "sg.finance.yahoo.com",
    "status": "blocked"
  },
  {
    "source": "spectrumlocalnews.com",
    "status": "alt",
    "alternative": "www.apnews.com"
  },
  {
    "source": "spfl.co.uk",
    "status": "direct"
  },
  {
    "source": "super.rugby",
    "status": "alt",
    "alternative": "www.espn.com"
  },
  {
    "source": "superliga.rs",
    "status": "alt",
    "alternative": "www.espn.com"
  },
  {
    "source": "superligaen.dk",
    "status": "direct"
  },
  {
    "source": "tff.org",
    "status": "direct"
  },
  {
    "source": "theahl.com",
    "status": "direct"
  },
  {
    "source": "thewll.com",
    "status": "blocked"
  },
  {
    "source": "truthsocial.com",
    "status": "direct"
  },
  {
    "source": "upl.ua",
    "status": "direct"
  },
  {
    "source": "vlr.gg",
    "status": "direct"
  },
  {
    "source": "weather.gov",
    "status": "direct"
  },
  {
    "source": "weather.gov.hk",
    "status": "direct"
  },
  {
    "source": "www.a-league.com.au",
    "status": "direct"
  },
  {
    "source": "www.aba-liga.com",
    "status": "alt",
    "alternative": "www.flashscore.com"
  },
  {
    "source": "www.acb.com",
    "status": "direct"
  },
  {
    "source": "www.aec.gov.au",
    "status": "direct"
  },
  {
    "source": "www.afa.com.ar",
    "status": "direct"
  },
  {
    "source": "www.aljazeera.com",
    "status": "blocked"
  },
  {
    "source": "www.allsvenskan.se",
    "status": "alt",
    "alternative": "www.espn.com"
  },
  {
    "source": "www.atptour.com",
    "status": "direct"
  },
  {
    "source": "www.banxico.org.mx",
    "status": "direct"
  },
  {
    "source": "www.billboard.com",
    "status": "direct"
  },
  {
    "source": "www.binance.com",
    "status": "direct"
  },
  {
    "source": "www.blackrock.com",
    "status": "alt",
    "alternative": "www.google.com/finance"
  },
  {
    "source": "www.bleague.jp",
    "status": "direct"
  },
  {
    "source": "www.bls.gov",
    "status": "blocked"
  },
  {
    "source": "www.bundesliga.at",
    "status": "alt",
    "alternative": "www.espn.com"
  },
  {
    "source": "www.bundesliga.com",
    "status": "direct"
  },
  {
    "source": "www.cbf.com.br",
    "status": "direct"
  },
  {
    "source": "www.cdc.gov",
    "status": "direct"
  },
  {
    "source": "www.championsleague.basketball",
    "status": "alt",
    "alternative": "www.flashscore.com"
  },
  {
    "source": "www.cnn.com",
    "status": "blocked"
  },
  {
    "source": "www.concacaf.com",
    "status": "direct"
  },
  {
    "source": "www.conmebol.com",
    "status": "direct"
  },
  {
    "source": "www.crunchyroll.com",
    "status": "direct"
  },
  {
    "source": "www.csl-china.com",
    "status": "direct"
  },
  {
    "source": "www.dotabuff.com",
    "status": "direct"
  },
  {
    "source": "www.easycredit-bbl.de",
    "status": "alt",
    "alternative": "www.flashscore.com"
  },
  {
    "source": "www.efa.com.eg",
    "status": "direct"
  },
  {
    "source": "www.efl.com",
    "status": "direct"
  },
  {
    "source": "www.electoralcommission.org.uk",
    "status": "direct"
  },
  {
    "source": "www.eliteserien.no",
    "status": "direct"
  },
  {
    "source": "www.epcrugby.com",
    "status": "alt",
    "alternative": "www.espn.com"
  },
  {
    "source": "www.esake.gr",
    "status": "alt",
    "alternative": "www.flashscore.com"
  },
  {
    "source": "www.espncricinfo.com",
    "status": "alt",
    "alternative": "www.espn.com"
  },
  {
    "source": "www.euroleaguebasketball.net",
    "status": "direct"
  },
  {
    "source": "www.fai.ie",
    "status": "alt",
    "alternative": "www.espn.com"
  },
  {
    "source": "www.fifa.com",
    "status": "direct"
  },
  {
    "source": "www.flashscore.com",
    "status": "direct"
  },
  {
    "source": "www.flashscoreusa.com",
    "status": "direct"
  },
  {
    "source": "www.football.org.il",
    "status": "alt",
    "alternative": "www.espn.com"
  },
  {
    "source": "www.formula1.com",
    "status": "direct"
  },
  {
    "source": "www.fortunaliga.cz",
    "status": "direct"
  },
  {
    "source": "www.frmf.ma",
    "status": "alt",
    "alternative": "www.flashscore.com"
  },
  {
    "source": "www.gettyimages.com.mx",
    "status": "direct"
  },
  {
    "source": "www.hltv.org",
    "status": "blocked"
  },
  {
    "source": "www.huya.com",
    "status": "direct"
  },
  {
    "source": "www.iihf.com",
    "status": "alt",
    "alternative": "www.flashscore.com"
  },
  {
    "source": "www.indec.gob.ar",
    "status": "blocked"
  },
  {
    "source": "www.indiansuperleague.com",
    "status": "direct"
  },
  {
    "source": "www.jleague.jp",
    "status": "direct"
  },
  {
    "source": "www.juntaelectoralcentral.es",
    "status": "direct"
  },
  {
    "source": "www.kbl.or.kr",
    "status": "direct"
  },
  {
    "source": "www.kick.com",
    "status": "direct"
  },
  {
    "source": "www.kleague.com",
    "status": "direct"
  },
  {
    "source": "www.koreabaseball.com",
    "status": "direct"
  },
  {
    "source": "www.kwqc.com",
    "status": "alt",
    "alternative": "www.apnews.com"
  },
  {
    "source": "www.laliga.com",
    "status": "direct"
  },
  {
    "source": "www.laliganacional.com.ar",
    "status": "alt",
    "alternative": "www.flashscore.com"
  },
  {
    "source": "www.legaseriea.it",
    "status": "direct"
  },
  {
    "source": "www.legaserieb.it",
    "status": "direct"
  },
  {
    "source": "www.ligagt.org",
    "status": "direct"
  },
  {
    "source": "www.ligaportugal.pt",
    "status": "direct"
  },
  {
    "source": "www.ligue1.com",
    "status": "direct"
  },
  {
    "source": "www.ligue2.fr",
    "status": "direct"
  },
  {
    "source": "www.lnb.fr",
    "status": "alt",
    "alternative": "www.flashscore.com"
  },
  {
    "source": "www.lnr.fr",
    "status": "alt",
    "alternative": "www.espn.com"
  },
  {
    "source": "www.lpf.ro",
    "status": "direct"
  },
  {
    "source": "www.mlb.com",
    "status": "direct"
  },
  {
    "source": "www.mlssoccer.com",
    "status": "direct"
  },
  {
    "source": "www.mlsz.hu",
    "status": "alt",
    "alternative": "www.espn.com"
  },
  {
    "source": "www.mostvaluablepromotions.com",
    "status": "alt",
    "alternative": "boxrec.com"
  },
  {
    "source": "www.natesilver.net",
    "status": "direct"
  },
  {
    "source": "www.nba.com",
    "status": "direct"
  },
  {
    "source": "www.ncei.noaa.gov",
    "status": "direct"
  },
  {
    "source": "www.nec.go.kr",
    "status": "direct"
  },
  {
    "source": "www.nhl.com",
    "status": "direct"
  },
  {
    "source": "www.nwslsoccer.com",
    "status": "direct"
  },
  {
    "source": "www.ons.gov.uk",
    "status": "direct"
  },
  {
    "source": "www.parliament.uk",
    "status": "direct"
  },
  {
    "source": "www.pgatour.com",
    "status": "direct"
  },
  {
    "source": "www.pglesports.com",
    "status": "direct"
  },
  {
    "source": "www.powerslap.com",
    "status": "blocked"
  },
  {
    "source": "www.premierleague.com",
    "status": "direct"
  },
  {
    "source": "www.premiershiprugby.com",
    "status": "alt",
    "alternative": "www.espn.com"
  },
  {
    "source": "www.prvaliga.si",
    "status": "alt",
    "alternative": "www.espn.com"
  },
  {
    "source": "www.rba.gov.au",
    "status": "direct"
  },
  {
    "source": "www.reuters.com",
    "status": "alt",
    "alternative": "www.apnews.com"
  },
  {
    "source": "www.rnc.org",
    "status": "alt",
    "alternative": "www.apnews.com"
  },
  {
    "source": "www.rolandgarros.com",
    "status": "direct"
  },
  {
    "source": "www.sec.gov",
    "status": "direct"
  },
  {
    "source": "www.slstat.com",
    "status": "direct"
  },
  {
    "source": "www.sooplive.com",
    "status": "blocked"
  },
  {
    "source": "www.strategy.com",
    "status": "direct"
  },
  {
    "source": "www.swpc.noaa.gov",
    "status": "direct"
  },
  {
    "source": "www.tbl.org.tr",
    "status": "blocked"
  },
  {
    "source": "www.the-numbers.com",
    "status": "direct"
  },
  {
    "source": "www.thefa.com",
    "status": "direct"
  },
  {
    "source": "www.thenationalleague.org.uk",
    "status": "direct"
  },
  {
    "source": "www.tsa.gov",
    "status": "direct"
  },
  {
    "source": "www.twitch.tv",
    "status": "direct"
  },
  {
    "source": "www.uefa.com",
    "status": "direct"
  },
  {
    "source": "www.ufc.com",
    "status": "direct"
  },
  {
    "source": "www.unafut.com",
    "status": "direct"
  },
  {
    "source": "www.unitedrugby.com",
    "status": "alt",
    "alternative": "www.espn.com"
  },
  {
    "source": "www.vlr.gg",
    "status": "direct"
  },
  {
    "source": "www.vtb-league.com",
    "status": "alt",
    "alternative": "www.flashscore.com"
  },
  {
    "source": "www.weather.gov",
    "status": "direct"
  },
  {
    "source": "www.weather.gov.hk",
    "status": "direct"
  },
  {
    "source": "www.wnba.com",
    "status": "direct"
  },
  {
    "source": "www.worldtabletennis.com",
    "status": "alt",
    "alternative": "www.flashscore.com"
  },
  {
    "source": "www.wsj.com",
    "status": "blocked"
  },
  {
    "source": "www.wtatennis.com",
    "status": "direct"
  },
  {
    "source": "www.wunderground.com",
    "status": "direct"
  },
  {
    "source": "www.youtube.com",
    "status": "direct"
  },
  {
    "source": "x.com",
    "status": "blocked"
  },
  {
    "source": "xtracker.polymarket.com",
    "status": "direct"
  }
],
};
