/**
 * Pulls the full sources-bench catalog from gym.genlayer.foundation and writes
 * it to src/lib/sources-catalog.generated.ts as the build-time fallback. The
 * runtime fetcher prefers a live call; this snapshot is used when the live
 * fetch fails or while developing offline.
 *
 * Usage (from repo root): npm run sync-sources
 */

import { writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const SOURCES_URL =
  "https://gym.genlayer.foundation/api/benchmarks/sources-bench/sources";

interface CatalogSource {
  source: string;
  status: "direct" | "alt" | "blocked";
  alternative?: string;
  reason?: string;
}

interface SourcesCatalog {
  generatedAt: string;
  count: number;
  sources: CatalogSource[];
}

async function main() {
  const res = await fetch(SOURCES_URL);
  if (!res.ok) {
    throw new Error(`Failed to fetch catalog: ${res.status} ${res.statusText}`);
  }
  const catalog = (await res.json()) as SourcesCatalog;
  if (!Array.isArray(catalog.sources)) {
    throw new Error("Catalog response missing `sources` array");
  }

  // Mirror the runtime sanitizer in src/lib/sources-catalog.ts so the snapshot
  // never embeds entries that would fail the trust-boundary check at request
  // time.
  const SAFE_HOST_RE = /^[a-zA-Z0-9._\-/]{1,200}$/;
  const safe = catalog.sources.filter((s) => {
    if (typeof s?.source !== "string" || !SAFE_HOST_RE.test(s.source)) return false;
    if (s.alternative !== undefined && !SAFE_HOST_RE.test(s.alternative)) return false;
    return s.status === "direct" || s.status === "alt" || s.status === "blocked";
  });
  const dropped = catalog.sources.length - safe.length;
  if (dropped > 0) {
    console.warn(`Dropped ${dropped} catalog entries that failed host-name sanitization.`);
  }
  const sorted = [...safe].sort((a, b) => a.source.localeCompare(b.source));

  const __dirname = dirname(fileURLToPath(import.meta.url));
  const outPath = resolve(__dirname, "../src/lib/sources-catalog.generated.ts");

  const minimal = sorted.map((s) => {
    const row: CatalogSource = { source: s.source, status: s.status };
    if (s.alternative) row.alternative = s.alternative;
    return row;
  });

  const file = `// Generated by tools/sync-sources-catalog.ts. Do not edit by hand.
// Source: ${SOURCES_URL}
// Catalog generated at: ${catalog.generatedAt}
// Synced at: ${new Date().toISOString()}

import type { SourcesCatalog } from "./sources-catalog";

export const FALLBACK_SOURCES_CATALOG: SourcesCatalog = {
  generatedAt: ${JSON.stringify(catalog.generatedAt)},
  count: ${minimal.length},
  sources: ${JSON.stringify(minimal, null, 2)},
};
`;

  writeFileSync(outPath, file);
  console.log(
    `Wrote ${minimal.length} sources to ${outPath} (catalog generated ${catalog.generatedAt}).`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
